version: '3.3'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=yardsale
            - POSTGRES_USER=geaglts
            - POSTGRES_PASSWORD=geaglts
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
    pg_admin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=geaglts@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=geaglts
        depends_on:
            - postgres
        ports:
            - 5050:80
